spring:
  application:
    name: space-events-bot
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: space_events_bot
launches:
  url: https://fdo.rocketlaunch.live/json/launches/next/5
news:
  url: https://api.spaceflightnewsapi.net/v4/articles/
apod:
  url: https://apod.ellanan.com/api
asteroids:
  url: https://api.nasa.gov/neo/rest/v1/feed
  api_key: ${NASA_API_KEY}
